update
update

diff --git a/.github/workflows/deploy-cdk.yml b/.github/workflows/deploy-cdk.yml
--- a/.github/workflows/deploy-cdk.yml
+++ b/.github/workflows/deploy-cdk.yml
@@ -8,10 +8,6 @@ jobs:
     if: github.event.pull_request.merged == true || github.event_name == 'push' || github.event_name == 'workflow_dispatch'
     runs-on: ubuntu-latest
 
-    defaults:
-      run:
-        working-directory: cdk
-
     steps:
       - name: Checkout repo
         uses: actions/checkout@v3
@@ -21,14 +17,22 @@ jobs:
         with:
           node-version: '18'
 
-      - name: Install dependencies
+      - name: Install CDK dependencies
+        working-directory: cdk
         run: npm install
+
+      - name: Debug Lambda bundling directory
+        run: |
+          echo "::group::Contents of Lambda source directory"
+          ls -lah backend/auth/add_user_to_groups
+          cat backend/auth/add_user_to_groups/requirements.txt || echo "Missing requirements.txt"
+          echo "::endgroup::"
 
       - name: CDK diff
         uses: youyo/aws-cdk-github-actions@v2
         with:
           cdk_subcommand: 'diff'
-          working_dir: './cdk'
+          working_dir: 'cdk'
           actions_comment: true
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -41,7 +45,7 @@ jobs:
           cdk_subcommand: 'deploy'
           cdk_stack: '*'
           cdk_args: '--require-approval never'
-          working_dir: './cdk'
+          working_dir: 'cdk'
           actions_comment: false
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
